apiVersion: batch/v1
kind: Job
metadata:
  name: create-database-job
spec:
  template:
    spec:
      containers:
        - name: create-database
          image: postgres:17
          env:
            - name: PGPASSWORD
              value: "{{ .Values.postgres.password }}"
          command: ["sh", "-c", "psql -h {{ .Values.postgres.host }} -U {{ .Values.postgres.user }} -c \"CREATE DATABASE IF NOT EXISTS {{ .Values.postgres.database }};\""]
        restartPolicy: Never
    backoffLimit: 4