apiVersion: batch/v1
kind: Job
metadata:
  name: create-database-job
spec:
  template:
    spec:
      containers:
        - name: create-database
          image: postgres:17
          env:
            - name: PGPASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: PGHOST
              value: "{{ .Values.postgres.host }}"
            - name: DATABASE_NAME
              value: "{{ .Values.postgres.database }}"
          command: 
            - sh
            - -c
            - |
              echo "Attempting to create database..."
              if psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$DATABASE_NAME'" | grep -q 1; then
                echo "Database already exists"
              else
                psql -U postgres -c "CREATE DATABASE $DATABASE_NAME;"
              fi

      restartPolicy: Never
  backoffLimit: 4